In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('Travel.csv')

In [5]:
df.head()

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   
2      200002          1  37.0     Self Enquiry         1              8.0   
3      200003          0  33.0  Company Invited         1              9.0   
4      200004          0   NaN     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

DATA CLEANING

In [7]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [11]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [12]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [13]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [14]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single ','Unmarried')

In [15]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [16]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [17]:
df.head()

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   
2      200002          1  37.0     Self Enquiry         1              8.0   
3      200003          0  33.0  Company Invited         1              9.0   
4      200004          0   NaN     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

In [18]:
features_with_na = [features for features in df.columns if df[features].isnull().sum()>1]
for feature in features_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5),'% missing values')

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values


In [22]:
df[features_with_na].select_dtypes(exclude=['object']).describe()

Age  DurationOfPitch  NumberOfFollowups  PreferredPropertyStar  \
count  4662.000000      4637.000000        4843.000000            4862.000000   
mean     37.622265        15.490835           3.708445               3.581037   
std       9.316387         8.519643           1.002509               0.798009   
min      18.000000         5.000000           1.000000               3.000000   
25%      31.000000         9.000000           3.000000               3.000000   
50%      36.000000        13.000000           4.000000               3.000000   
75%      44.000000        20.000000           4.000000               4.000000   
max      61.000000       127.000000           6.000000               5.000000   

       NumberOfTrips  NumberOfChildrenVisiting  MonthlyIncome  
count    4748.000000               4822.000000    4655.000000  
mean        3.236521                  1.187267   23619.853491  
std         1.849019                  0.857861    5380.698361  
min         1.000000                  0.000000    1000.000000  
25%         2.000000                  1.000000   20346.000000  
50%         3.000000                  1.000000   22347.000000  
75%         4.000000                  2.000000   25571.000000  
max        22.000000                  3.000000   98678.000000

In [31]:
df.Age.fillna(df.Age.median(),inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.mean(),inplace=True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
df.NumberOfTrips.fillna(df.NumberOfTrips.mode()[0],inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)
df.NumberOfTrips.fillna(0,inplace=True)
df.NumberOfChildrenVisiting.fillna(0,inplace=True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)
df.NumberOfTrips.fillna(0,inplace=True)


In [32]:
df.head()

CustomerID  ProdTaken        Age    TypeofContact  CityTier  \
0      200000          1  41.000000     Self Enquiry         3   
1      200001          0  49.000000  Company Invited         1   
2      200002          1  37.000000     Self Enquiry         1   
3      200003          0  33.000000  Company Invited         1   
4      200004          0  37.622265     Self Enquiry         1   

   DurationOfPitch      Occupation  Gender  NumberOfPersonVisiting  \
0              6.0        Salaried  Female                       3   
1             14.0        Salaried    Male                       3   
2              8.0     Free Lancer    Male                       3   
3              9.0        Salaried  Female                       2   
4              8.0  Small Business    Male                       2   

   NumberOfFollowups ProductPitched  PreferredPropertyStar MaritalStatus  \
0                3.0         Deluxe                    3.0        Single   
1                4.0         Deluxe                    4.0      Divorced   
2                4.0          Basic                    3.0        Single   
3                3.0          Basic                    3.0      Divorced   
4                3.0          Basic                    4.0      Divorced   

   NumberOfTrips  Passport  PitchSatisfactionScore  OwnCar  \
0            1.0         1                       2       1   
1            2.0         0                       3       1   
2            7.0         1                       3       0   
3            2.0         1                       5       1   
4            1.0         0                       5       1   

   NumberOfChildrenVisiting Designation  MonthlyIncome  
0                       0.0     Manager        20993.0  
1                       2.0     Manager        20130.0  
2                       0.0   Executive        17090.0  
3                       1.0   Executive        17909.0  
4                       0.0   Executive        18468.0

In [33]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [35]:
df.drop('CustomerID' , inplace = True , axis =1)

In [36]:
df.head()

ProdTaken        Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.000000     Self Enquiry         3              6.0   
1          0  49.000000  Company Invited         1             14.0   
2          1  37.000000     Self Enquiry         1              8.0   
3          0  33.000000  Company Invited         1              9.0   
4          0  37.622265     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

In [37]:
df['TotalVisiting'] = df['NumberOfChildrenVisiting'] + df['NumberOfPersonVisiting']

In [38]:
df.drop(columns=['NumberOfChildrenVisiting','NumberOfPersonVisiting'],inplace=True)

In [39]:
df.head()

ProdTaken        Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.000000     Self Enquiry         3              6.0   
1          0  49.000000  Company Invited         1             14.0   
2          1  37.000000     Self Enquiry         1              8.0   
3          0  33.000000  Company Invited         1              9.0   
4          0  37.622265     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0        Single            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0        Single            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  TotalVisiting  
0                       2       1     Manager        20993.0            3.0  
1                       3       1     Manager        20130.0            5.0  
2                       3       0   Executive        17090.0            3.0  
3                       5       1   Executive        17909.0            3.0  
4                       5       1   Executive        18468.0            2.0

In [40]:
num_features = [feature in df.columns for feature in df.columns if df[feature].dtype != 'O']
print('Num of numerical features', len(num_features))

Num of numerical features 12


In [41]:
cat_features = [features for features in df.columns if df[features].dtype == 'O']
print('Num of categorical features', len(cat_features))

Num of categorical features 6


In [46]:
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of numerical features', len(num_features))

discrete_feature = [feature for feature in num_features if len(df[feature].unique())<25]
print('Num of discrete features', len(discrete_feature))

Num of numerical features 12
Num of discrete features 9


In [47]:
continous_feature = [feature for feature in num_features if feature not in discrete_feature]
print('Num of continuous features', len(continous_feature))

Num of continuous features 3


In [48]:
from sklearn.model_selection import train_test_split

In [52]:
X = df.drop(['ProdTaken'] , axis = 1)
y = df['ProdTaken']

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((3421, 17), (1467, 17), (3421,), (1467,))

In [54]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [55]:
X.head()

Age    TypeofContact  CityTier  DurationOfPitch      Occupation  \
0  41.000000     Self Enquiry         3              6.0        Salaried   
1  49.000000  Company Invited         1             14.0        Salaried   
2  37.000000     Self Enquiry         1              8.0     Free Lancer   
3  33.000000  Company Invited         1              9.0        Salaried   
4  37.622265     Self Enquiry         1              8.0  Small Business   

   Gender  NumberOfFollowups ProductPitched  PreferredPropertyStar  \
0  Female                3.0         Deluxe                    3.0   
1    Male                4.0         Deluxe                    4.0   
2    Male                4.0          Basic                    3.0   
3  Female                3.0          Basic                    3.0   
4    Male                3.0          Basic                    4.0   

  MaritalStatus  NumberOfTrips  Passport  PitchSatisfactionScore  OwnCar  \
0        Single            1.0         1                       2       1   
1      Divorced            2.0         0                       3       1   
2        Single            7.0         1                       3       0   
3      Divorced            2.0         1                       5       1   
4      Divorced            1.0         0                       5       1   

  Designation  MonthlyIncome  TotalVisiting  
0     Manager        20993.0            3.0  
1     Manager        20130.0            5.0  
2   Executive        17090.0            3.0  
3   Executive        17909.0            3.0  
4   Executive        18468.0            2.0

In [56]:
cat_features = X.select_dtypes(include='object').columns
num_features = X.select_dtypes(exclude='object').columns

In [57]:
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer

In [58]:
numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

In [59]:
preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,cat_features),
        ('StandardScaler',numeric_transformer,num_features)
    ]
)

In [63]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [75]:
X_train

array([[ 1.        ,  0.        ,  1.        , ...,  0.78143477,
         0.4603181 , -0.05748917],
       [ 1.        ,  1.        ,  0.        , ..., -1.27969734,
        -1.00566841, -0.76493678],
       [ 1.        ,  0.        ,  1.        , ...,  0.78143477,
        -1.2097217 , -0.05748917],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.35739958,  0.64995845],
       [ 1.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.25076528,  0.64995845],
       [ 0.        ,  0.        ,  1.        , ..., -1.27969734,
        -1.07168012, -1.47238439]])

In [69]:
X_test

array([[ 0.        ,  0.        ,  1.        , ..., -1.27449173,
        -0.76431965, -0.74322714],
       [ 1.        ,  0.        ,  1.        , ..., -1.27449173,
        -0.69530474, -0.04520267],
       [ 1.        ,  0.        ,  1.        , ...,  0.78462651,
        -0.43860055, -0.74322714],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.78462651,
        -0.08902926, -0.04520267],
       [ 1.        ,  1.        ,  0.        , ...,  0.78462651,
         2.04886893, -0.04520267],
       [ 1.        ,  1.        ,  0.        , ..., -1.27449173,
         1.3342811 , -1.4412516 ]])

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [79]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report, recall_score , f1_score , precision_score , roc_auc_score , roc_curve

In [80]:
models ={
    "Random Forest" : RandomForestClassifier(),
    "Logistic Regression" : LogisticRegression(),
    "Decision Tree" : DecisionTreeClassifier()
}


for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)



    print(list(models.keys())[i])
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print(f1_score(y_test,y_pred))
    print(recall_score(y_test,y_pred))
    print(precision_score(y_test,y_pred))
    print(roc_auc_score(y_test,y_pred))

Random Forest
0.9161554192229039
[[1180   13]
 [ 110  164]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95      1193
           1       0.93      0.60      0.73       274

    accuracy                           0.92      1467
   macro avg       0.92      0.79      0.84      1467
weighted avg       0.92      0.92      0.91      1467

0.7272727272727273
0.5985401459854015
0.9265536723163842
0.7938216237051902
Logistic Regression
0.8411724608043627
[[1147   46]
 [ 187   87]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      1193
           1       0.65      0.32      0.43       274

    accuracy                           0.84      1467
   macro avg       0.76      0.64      0.67      1467
weighted avg       0.82      0.84      0.82      1467

0.4275184275184275
0.3175182481751825
0.6541353383458647
0.6394799958394771
Decision Tree
0.8902522154055896
[[1110   83]
 [  78  196]]
        

HYPERPARAMETER TUNING

In [83]:
rf_params ={
    "max_depth" : [5, 8, 15, None , 10],
    "n_estimators" : [10,100,200,500],
    "max_features" : [5, 7 , "auto" , 8],
    'min_samples_split' : [2, 8, 15, 20]
}

In [84]:
rf_params

{'max_depth': [5, 8, 15, None, 10],
 'n_estimators': [10, 100, 200, 500],
 'max_features': [5, 7, 'auto', 8],
 'min_samples_split': [2, 8, 15, 20]}

In [85]:
randomcv_models = [
    ("RF" , RandomForestClassifier(),rf_params)
]

In [86]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 8, 15, None, 10],
   'n_estimators': [10, 100, 200, 500],
   'max_features': [5, 7, 'auto', 8],
   'min_samples_split': [2, 8, 15, 20]})]

In [87]:
from sklearn.model_selection import RandomizedSearchCV

In [88]:
model_params = {}
for name , model , params in randomcv_models:
  random = RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=100,cv=3,verbose=2,n_jobs=-1)
  random.fit(X_train,y_train)
  model_params[name] = random.best_params_

for model_name in model_params:
  print(f"Best params for {model_name} is {model_params[model_name]}")


Fitting 3 folds for each of 100 candidates, totalling 300 fits
Best params for RF is {'n_estimators': 100, 'min_samples_split': 2, 'max_features': 8, 'max_depth': 15}


In [91]:
models ={
    "Random Forest" : RandomForestClassifier(n_estimators=200,max_depth=5,max_features=8,min_samples_split=2)
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)



    print(list(models.keys())[i])
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print(f1_score(y_test,y_pred))
    print(recall_score(y_test,y_pred))
    print(precision_score(y_test,y_pred))
    print(roc_auc_score(y_test,y_pred))

Random Forest
0.8425357873210634
[[1175   18]
 [ 213   61]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91      1193
           1       0.77      0.22      0.35       274

    accuracy                           0.84      1467
   macro avg       0.81      0.60      0.63      1467
weighted avg       0.83      0.84      0.80      1467

0.34560906515580736
0.22262773722627738
0.7721518987341772
0.6037698619073549
