In [3]:
## Dataset(Tips Dataset)
import seaborn as sns
df = sns.load_dataset('tips')

In [4]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [7]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [8]:
df.describe

<bound method NDFrame.describe of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [9]:
df['smoker'].value_counts

<bound method IndexOpsMixin.value_counts of 0       No
1       No
2       No
3       No
4       No
      ... 
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): ['Yes', 'No']>

In [10]:
df['time'].value_counts

<bound method IndexOpsMixin.value_counts of 0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']>

FEATURE ENCODING(LABEL ENCODING AND ONEHOT ENCODING)

In [11]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [12]:
X = df[['tip', 'sex', 'smoker','day', 'time', 'size']]
y = df['total_bill']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [15]:
X_train

tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2
..    ...     ...    ...  ...     ...   ...
106  4.06    Male    Yes  Sat  Dinner     2
14   3.02  Female     No  Sun  Dinner     2
92   1.00  Female    Yes  Fri  Dinner     2
179  3.55    Male    Yes  Sun  Dinner     2
102  2.50  Female    Yes  Sat  Dinner     3

[183 rows x 6 columns]

In [16]:
X.shape

(244, 6)

In [17]:
X_train.shape

(183, 6)

FEATURE ENCODING

In [18]:
X_train.head()

tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2

In [19]:
from sklearn.preprocessing import LabelEncoder

In [21]:
import warnings
warnings.filterwarnings('ignore')

le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [22]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

In [23]:
X_test.head()

tip     sex smoker   day    time  size
24   3.18    Male     No   Sat  Dinner     2
6    2.00    Male     No   Sun  Dinner     2
153  2.00    Male     No   Sun  Dinner     4
211  5.16    Male    Yes   Sat  Dinner     4
198  2.00  Female    Yes  Thur   Lunch     2

ONEHOT ENCODING -- COLUMN TRANSFORMER

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [30]:
ct = ColumnTransformer(transformers= [('onehot' , OneHotEncoder(drop='first'), [3])] ,remainder='passthrough')

In [31]:
ct.fit_transform(X_train)

array([[0., 1., 0., ..., 0., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [0., 0., 0., ..., 1., 1., 2.],
       ...,
       [0., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 3.]])

In [38]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
ct.fit_transform(X_train)


array([[ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.65,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.01,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  4.08,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.09,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  3.41,  1.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  3.48,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  ,  2.71,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.

In [40]:
X_test

array([[1.0, 0.0, 0.0, 3.18, 'Male', 'No', 'Dinner', 2],
       [0.0, 1.0, 0.0, 2.0, 'Male', 'No', 'Dinner', 2],
       [0.0, 1.0, 0.0, 2.0, 'Male', 'No', 'Dinner', 4],
       [1.0, 0.0, 0.0, 5.16, 'Male', 'Yes', 'Dinner', 4],
       [0.0, 0.0, 1.0, 2.0, 'Female', 'Yes', 'Lunch', 2],
       [0.0, 1.0, 0.0, 2.0, 'Male', 'Yes', 'Dinner', 2],
       [0.0, 0.0, 1.0, 2.56, 'Male', 'Yes', 'Lunch', 2],
       [0.0, 0.0, 1.0, 2.52, 'Female', 'No', 'Lunch', 2],
       [0.0, 1.0, 0.0, 3.23, 'Male', 'No', 'Dinner', 2],
       [0.0, 0.0, 0.0, 3.0, 'Female', 'Yes', 'Dinner', 2],
       [0.0, 1.0, 0.0, 3.0, 'Male', 'No', 'Dinner', 2],
       [1.0, 0.0, 0.0, 1.47, 'Male', 'No', 'Dinner', 2],
       [0.0, 0.0, 1.0, 1.5, 'Female', 'No', 'Lunch', 2],
       [0.0, 1.0, 0.0, 2.0, 'Male', 'Yes', 'Dinner', 2],
       [0.0, 0.0, 1.0, 1.83, 'Female', 'No', 'Lunch', 1],
       [0.0, 0.0, 1.0, 1.36, 'Female', 'No', 'Lunch', 3],
       [0.0, 0.0, 1.0, 4.0, 'Male', 'Yes', 'Lunch', 3],
       [0.0, 1.0, 0.0, 3.92,