In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [8]:
df = pd.read_csv('Travel.csv')

In [ ]:
df.head()

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   
2      200002          1  37.0     Self Enquiry         1              8.0   
3      200003          0  33.0  Company Invited         1              9.0   
4      200004          0   NaN     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

DATA CLEANING

In [9]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [10]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [11]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [12]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [13]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')
df['MaritalStatus'] = df['MaritalStatus'].replace('Single ','Unmarried')

In [14]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [15]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [16]:
df.head()

CustomerID  ProdTaken  ...  Designation MonthlyIncome
0      200000          1  ...      Manager       20993.0
1      200001          0  ...      Manager       20130.0
2      200002          1  ...    Executive       17090.0
3      200003          0  ...    Executive       17909.0
4      200004          0  ...    Executive       18468.0

[5 rows x 20 columns]

In [17]:
features_with_na = [features for features in df.columns if df[features].isnull().sum()>1]
for feature in features_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5),'% missing values')

Age 4.62357 % missing values
TypeofContact 0.51146 % missing values
DurationOfPitch 5.13502 % missing values
NumberOfFollowups 0.92062 % missing values
PreferredPropertyStar 0.53191 % missing values
NumberOfTrips 2.86416 % missing values
NumberOfChildrenVisiting 1.35025 % missing values
MonthlyIncome 4.76678 % missing values


In [18]:
df[features_with_na].select_dtypes(exclude=['object']).describe()

Age  DurationOfPitch  ...  NumberOfChildrenVisiting  MonthlyIncome
count  4662.000000      4637.000000  ...               4822.000000    4655.000000
mean     37.622265        15.490835  ...                  1.187267   23619.853491
std       9.316387         8.519643  ...                  0.857861    5380.698361
min      18.000000         5.000000  ...                  0.000000    1000.000000
25%      31.000000         9.000000  ...                  1.000000   20346.000000
50%      36.000000        13.000000  ...                  1.000000   22347.000000
75%      44.000000        20.000000  ...                  2.000000   25571.000000
max      61.000000       127.000000  ...                  3.000000   98678.000000

[8 rows x 7 columns]

In [19]:
df.Age.fillna(df.Age.median(),inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.mean(),inplace=True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
df.NumberOfTrips.fillna(df.NumberOfTrips.mode()[0],inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)
df.NumberOfTrips.fillna(0,inplace=True)
df.NumberOfChildrenVisiting.fillna(0,inplace=True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)
df.NumberOfTrips.fillna(0,inplace=True)


In [20]:
df.head()

CustomerID  ProdTaken  ...  Designation MonthlyIncome
0      200000          1  ...      Manager       20993.0
1      200001          0  ...      Manager       20130.0
2      200002          1  ...    Executive       17090.0
3      200003          0  ...    Executive       17909.0
4      200004          0  ...    Executive       18468.0

[5 rows x 20 columns]

In [21]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [22]:
df.drop('CustomerID' , inplace = True , axis =1)

In [23]:
df.head()

ProdTaken   Age  ... Designation  MonthlyIncome
0          1  41.0  ...     Manager        20993.0
1          0  49.0  ...     Manager        20130.0
2          1  37.0  ...   Executive        17090.0
3          0  33.0  ...   Executive        17909.0
4          0  36.0  ...   Executive        18468.0

[5 rows x 19 columns]

In [24]:
df['TotalVisiting'] = df['NumberOfChildrenVisiting'] + df['NumberOfPersonVisiting']

In [25]:
df.drop(columns=['NumberOfChildrenVisiting','NumberOfPersonVisiting'],inplace=True)

In [26]:
df.head()

ProdTaken   Age    TypeofContact  ...  Designation  MonthlyIncome TotalVisiting
0          1  41.0     Self Enquiry  ...      Manager        20993.0           3.0
1          0  49.0  Company Invited  ...      Manager        20130.0           5.0
2          1  37.0     Self Enquiry  ...    Executive        17090.0           3.0
3          0  33.0  Company Invited  ...    Executive        17909.0           3.0
4          0  36.0     Self Enquiry  ...    Executive        18468.0           2.0

[5 rows x 18 columns]

In [27]:
num_features = [feature in df.columns for feature in df.columns if df[feature].dtype != 'O']
print('Num of numerical features', len(num_features))

Num of numerical features 12


In [28]:
cat_features = [features for features in df.columns if df[features].dtype == 'O']
print('Num of categorical features', len(cat_features))

Num of categorical features 6


In [29]:
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of numerical features', len(num_features))

discrete_feature = [feature for feature in num_features if len(df[feature].unique())<25]
print('Num of discrete features', len(discrete_feature))

Num of numerical features 12
Num of discrete features 9


In [30]:
continous_feature = [feature for feature in num_features if feature not in discrete_feature]
print('Num of continuous features', len(continous_feature))

Num of continuous features 3


In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X = df.drop(['ProdTaken'] , axis = 1)
y = df['ProdTaken']

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((3421, 17), (1467, 17), (3421,), (1467,))

In [34]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [35]:
X.head()

Age    TypeofContact  CityTier  ...  Designation MonthlyIncome TotalVisiting
0  41.0     Self Enquiry         3  ...      Manager       20993.0           3.0
1  49.0  Company Invited         1  ...      Manager       20130.0           5.0
2  37.0     Self Enquiry         1  ...    Executive       17090.0           3.0
3  33.0  Company Invited         1  ...    Executive       17909.0           3.0
4  36.0     Self Enquiry         1  ...    Executive       18468.0           2.0

[5 rows x 17 columns]

In [36]:
cat_features = X.select_dtypes(include='object').columns
num_features = X.select_dtypes(exclude='object').columns

In [37]:
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer

In [38]:
numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

In [39]:
preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,cat_features),
        ('StandardScaler',numeric_transformer,num_features)
    ]
)

In [40]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [41]:
X_train

Age    TypeofContact  ...  MonthlyIncome  TotalVisiting
736   48.0     Self Enquiry  ...        25999.0            4.0
1615  30.0     Self Enquiry  ...        18204.0            3.0
336   29.0     Self Enquiry  ...        17119.0            4.0
4526  29.0     Self Enquiry  ...        23457.0            5.0
2665  34.0     Self Enquiry  ...        21300.0            4.0
...    ...              ...  ...            ...            ...
4426  28.0     Self Enquiry  ...        20723.0            5.0
466   41.0     Self Enquiry  ...        31595.0            4.0
3092  38.0  Company Invited  ...        21651.0            5.0
3772  28.0     Self Enquiry  ...        22218.0            5.0
860   22.0  Company Invited  ...        17853.0            2.0

[3421 rows x 17 columns]

In [42]:
X_test

Age    TypeofContact  ...  MonthlyIncome  TotalVisiting
144   32.0  Company Invited  ...        19668.0            3.0
79    46.0     Self Enquiry  ...        20021.0            4.0
2098  37.0     Self Enquiry  ...        21334.0            3.0
4738  43.0     Self Enquiry  ...        22950.0            5.0
2858  25.0     Self Enquiry  ...        21880.0            7.0
...    ...              ...  ...            ...            ...
2570  59.0     Self Enquiry  ...        28990.0            5.0
3901  41.0     Self Enquiry  ...        20679.0            6.0
3364  35.0  Company Invited  ...        23122.0            4.0
3639  50.0     Self Enquiry  ...        34057.0            4.0
1962  48.0     Self Enquiry  ...        30402.0            2.0

[1467 rows x 17 columns]

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report, recall_score , f1_score , precision_score , roc_auc_score , roc_curve

In [45]:
models ={
    "Random Forest" : RandomForestClassifier(),
    "Logistic Regression" : LogisticRegression(),
    "Decision Tree" : DecisionTreeClassifier(),
    "Gradient Boosting" : GradientBoostingClassifier(),
    "Ada Boosting" : AdaBoostClassifier()
}


for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)



    print(list(models.keys())[i])
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print(f1_score(y_test,y_pred))
    print(recall_score(y_test,y_pred))
    print(precision_score(y_test,y_pred))
    print(roc_auc_score(y_test,y_pred))

Random Forest
0.9120654396728016
[[1181   12]
 [ 117  157]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95      1193
           1       0.93      0.57      0.71       274

    accuracy                           0.91      1467
   macro avg       0.92      0.78      0.83      1467
weighted avg       0.91      0.91      0.90      1467

0.708803611738149
0.572992700729927
0.9289940828402367
0.7814670125611077
Logistic Regression
0.8411724608043627
[[1147   46]
 [ 187   87]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      1193
           1       0.65      0.32      0.43       274

    accuracy                           0.84      1467
   macro avg       0.76      0.64      0.67      1467
weighted avg       0.82      0.84      0.82      1467

0.4275184275184275
0.3175182481751825
0.6541353383458647
0.6394799958394771
Decision Tree
0.8902522154055896
[[1106   87]
 [  74  200]]
          

HYPERPARAMETER TUNING

In [47]:
rf_params ={
    "max_depth" : [5, 8, 15, None , 10],
    "n_estimators" : [10,100,200,500],
    "max_features" : [5, 7 , "auto" , 8],
    'min_samples_split' : [2, 8, 15, 20]
}
ada_params = {
    "n_estimators" : [10,100,200,500],
    "learning_rate" : [0.001,0.01,0.1],
    "algorithm": ['SAMME' , 'SAMME.R']
}

In [ ]:
rf_params

{'max_depth': [5, 8, 15, None, 10],
 'n_estimators': [10, 100, 200, 500],
 'max_features': [5, 7, 'auto', 8],
 'min_samples_split': [2, 8, 15, 20]}

In [48]:
ada_params

{'n_estimators': [10, 100, 200, 500],
 'learning_rate': [0.001, 0.01, 0.1],
 'algorithm': ['SAMME', 'SAMME.R']}

In [49]:
randomcv_models = [
    ("RF" , RandomForestClassifier(),rf_params),
    ("AB" , AdaBoostClassifier() ,ada_params)
]

In [50]:
randomcv_models

[('RF',
  RandomForestClassifier(),
  {'max_depth': [5, 8, 15, None, 10],
   'n_estimators': [10, 100, 200, 500],
   'max_features': [5, 7, 'auto', 8],
   'min_samples_split': [2, 8, 15, 20]}),
 ('AB',
  AdaBoostClassifier(),
  {'n_estimators': [10, 100, 200, 500],
   'learning_rate': [0.001, 0.01, 0.1],
   'algorithm': ['SAMME', 'SAMME.R']})]

In [51]:
from sklearn.model_selection import RandomizedSearchCV

In [52]:
model_params = {}
for name , model , params in randomcv_models:
  random = RandomizedSearchCV(estimator=model,param_distributions=params,n_iter=100,cv=3,verbose=2,n_jobs=-1)
  random.fit(X_train,y_train)
  model_params[name] = random.best_params_

for model_name in model_params:
  print(f"Best params for {model_name} is {model_params[model_name]}")


Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 24 candidates, totalling 72 fits
Best params for RF is {'n_estimators': 500, 'min_samples_split': 2, 'max_features': 7, 'max_depth': 15}
Best params for AB is {'n_estimators': 500, 'learning_rate': 0.1, 'algorithm': 'SAMME'}


In [54]:
models ={
    "Random Forest" : RandomForestClassifier(n_estimators=200,max_depth=5,max_features=8,min_samples_split=2),
    "Adaboost" : AdaBoostClassifier(n_estimators=100,learning_rate=0.1,algorithm='SAMME')
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)



    print(list(models.keys())[i])
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print(f1_score(y_test,y_pred))
    print(recall_score(y_test,y_pred))
    print(precision_score(y_test,y_pred))
    print(roc_auc_score(y_test,y_pred))

Random Forest
0.8398091342876619
[[1176   17]
 [ 218   56]]
              precision    recall  f1-score   support

           0       0.84      0.99      0.91      1193
           1       0.77      0.20      0.32       274

    accuracy                           0.84      1467
   macro avg       0.81      0.60      0.62      1467
weighted avg       0.83      0.84      0.80      1467

0.3227665706051873
0.20437956204379562
0.7671232876712328
0.5950648857997687
Adaboost
0.8248125426039536
[[1191    2]
 [ 255   19]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90      1193
           1       0.90      0.07      0.13       274

    accuracy                           0.82      1467
   macro avg       0.86      0.53      0.52      1467
weighted avg       0.84      0.82      0.76      1467

0.1288135593220339
0.06934306569343066
0.9047619047619048
0.533833309879406
